name: Android CI

on:
  workflow_dispatch
     inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: true
        type: string
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: jacoco code coverage report
      run: ./gradlew clean jacocoTestReport
    - name: Upload report
      uses: actions/upload-artifact@v3
      with:
        name: reportFile
        path: app/build/jacoco/jacocoTestReport
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build debug APK
      run: bash ./gradlew assembleDebug --stacktrace
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
          name: ApkFile
          path: app/build/outputs/apk/debug/app-debug.apk

